[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
milestone_escrow = "6PisfLVTpenAEvaZmSSswrf2hZy6F3YZ6zvHqBZDMXna"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha --extension ts --timeout 1000000 tests/ --node-option disable-warning=ExperimentalWarning"

[hooks]
