// Bytes of the attested request parameters around the URL.
//
// GENERATED by scripts/gen-proof-constants.ts from fixtures/proof-pr-merged.json.
// Do not edit by hand.
use anchor_lang::prelude::*;

#[constant]
pub const PROOF_PROVIDER: &str = "http";

#[constant]
pub const PROOF_PARAMS_BEFORE_URL: &str = "{\"body\":\"\",\"method\":\"GET\",\"responseMatches\":[{\"type\":\"contains\",\"value\":\"\\\"merged_at\\\":\\\"2\"}],\"responseRedactions\":[],\"url\":\"";

#[constant]
pub const PROOF_PARAMS_AFTER_URL: &str = "\"}";
