// The program's IDL, as generated by Dev A and copied into app/src/idl/ by scripts/idl-sync.ts.
// The program ID defaults to the IDL's address and can be overridden with VITE_PROGRAM_ID.
import { PublicKey } from "@solana/web3.js";
import rawIdl from "../idl/milestone_escrow.json";
import type { MilestoneEscrow } from "../idl/milestone_escrow";
import { PROGRAM_ID_OVERRIDE } from "./env";

export type { MilestoneEscrow };

export const IDL: MilestoneEscrow = {
  ...(rawIdl as unknown as MilestoneEscrow),
  address: (PROGRAM_ID_OVERRIDE ||
    rawIdl.address) as MilestoneEscrow["address"],
};

export const PROGRAM_ID = new PublicKey(IDL.address);

/** Error names declared by the program, keyed by their numeric code. */
export const PROGRAM_ERRORS: ReadonlyMap<number, string> = new Map(
  rawIdl.errors.map((e) => [e.code, e.name] as const),
);
