// Regenerates programs/milestone_escrow/src/proof/generated.rs from a real
// attestor proof (fixtures/proof-pr-merged.json, produced by the proof spike),
// so the parameter bytes the program rebuilds are exactly the ones signed.
//   node scripts/gen-proof-constants.ts [fixture]
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const root = join(dirname(new URL(import.meta.url).pathname), "..");
const fixturePath =
  process.argv[2] ?? join(root, "fixtures/proof-pr-merged.json");

type Fixture = { claimData: { provider: string; parameters: string } };
const { claimData } = JSON.parse(readFileSync(fixturePath, "utf8")) as Fixture;

const params = claimData.parameters;
const url = (JSON.parse(params) as { url: string }).url;
if (
  !/^https:\/\/api\.github\.com\/repos\/[^/]+\/[^/]+\/issues\/\d+$/.test(url)
) {
  throw new Error(`unexpected proof URL: ${url}`);
}
const at = params.indexOf(url);
if (at < 0 || params.indexOf(url, at + 1) >= 0) {
  throw new Error("the URL must occur exactly once in the parameters");
}

// JSON string escaping is valid Rust string-literal escaping for this input.
const rust = (s: string) => JSON.stringify(s);
const out = `// Bytes of the attested request parameters around the URL.
//
// GENERATED by scripts/gen-proof-constants.ts from ${fixturePath.replace(root + "/", "")}.
// Do not edit by hand.
use anchor_lang::prelude::*;

#[constant]
pub const PROOF_PROVIDER: &str = ${rust(claimData.provider)};

#[constant]
pub const PROOF_PARAMS_BEFORE_URL: &str = ${rust(params.slice(0, at))};

#[constant]
pub const PROOF_PARAMS_AFTER_URL: &str = ${rust(params.slice(at + url.length))};
`;
writeFileSync(
  join(root, "programs/milestone_escrow/src/proof/generated.rs"),
  out,
);
console.log(
  "wrote proof/generated.rs; rebuild and run node scripts/idl-sync.ts",
);
